version: '3.8'
services:
  api:
    container_name: "sii_parse"
    image: "sii_parse"
    build:
      context: ./app
      target: "dev"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:dev"]
    env_file:
      - .env
    ports:
      - 35515:35515
    networks:
      - nestjs-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  nestjs-network:
